copying
copyFromKeep: anotherMe
	"discard me"
	startTime := anotherMe startTime.
	endTime := anotherMe endTime.
	numOpenCases			:= anotherMe numOpenCases.
	numOpenedCases			:= anotherMe numOpenedCases.
	numClosedCases	 		:= anotherMe numClosedCases.
	numReopenedCases		:= anotherMe numReopenedCases.
	numResolvedCases 		:= anotherMe numResolvedCases.
	numResponsibleSetCases	:= anotherMe numResponsibleSetCases.

	totalTimeToOpen				:= anotherMe totalTimeToOpen.
	totalTimeToClose				:= anotherMe totalTimeToClose.
	totalPeriodOpen				:= anotherMe totalPeriodOpen.
	totalTimeToSetResponsible	:= anotherMe totalTimeToSetResponsible.
	totalTimeToResolution		:= anotherMe totalTimeToResolution.
	totalPeriodForResolutionValidation := anotherMe totalPeriodForResolutionValidation.