as yet unclassified
sourceStyle
	^'
.halo-source .html-source {
	font-family: courier, serif;
	font-size: 9pt;
}

.halo-source .xmlDeclaration {
	color: limegreen;
	font-style: italic;
}

.halo-source .doctype {
	color: skyblue;
	font-style: italic;
}

.halo-source .tag-known {
	color: purple;
	font-weight: bold;
}

.halo-source .attribute-known {
	font-weight: bold;
}

.halo-source .attribute-value {
	color: blue;
}

.halo-source .template {
	color: blue;
	font-weight: bold;
}

'