edit
renderIntroductionOn: html
  html
    paragraph:
      'This is your personal view of Nextround. Here you have list of all the things you have created in the system like your personal profile, and businesses and assessments. There is also a list of cases that you are currently responsible for. This usually contains tasks set for businesses by your Scaling Guide, but can include other things. There is also a free text search box to help find things if you have a lot going on within Nextround. Position the mouse over the table headings to see more detailed descriptions.'