SystemOrganization addCategory: #'Q2'!
SystemOrganization addCategory: #'Q2-Domain'!
SystemOrganization addCategory: #'Q2-Domain-events'!
SystemOrganization addCategory: #'Q2-Domain-exceptions'!
SystemOrganization addCategory: #'Q2-Domain-filters'!
SystemOrganization addCategory: #'Q2-Domain-forms'!
SystemOrganization addCategory: #'Q2-Domain-forms-accessors'!
SystemOrganization addCategory: #'Q2-Domain-mirroring'!
SystemOrganization addCategory: #'Q2-Domain-mirroring-tests'!
SystemOrganization addCategory: #'Q2-Domain-reports'!
SystemOrganization addCategory: #'Q2-Domain-settings'!
SystemOrganization addCategory: #'Q2-Domain-Statistics'!
SystemOrganization addCategory: #'Q2-Libraries'!
SystemOrganization addCategory: #'Q2-Morphic'!
SystemOrganization addCategory: #'Q2-MorphicTools'!
SystemOrganization addCategory: #'Q2-Plugins'!
SystemOrganization addCategory: #'Q2-Scheduler'!
SystemOrganization addCategory: #'Q2-Seaside UI'!
SystemOrganization addCategory: #'Q2-Seaside UI-base'!
SystemOrganization addCategory: #'Q2-Seaside UI-errorhandling'!
SystemOrganization addCategory: #'Q2-Seaside UI-forms'!
SystemOrganization addCategory: #'Q2-Seaside-addons'!
SystemOrganization addCategory: #'Q2-Serialization'!
SystemOrganization addCategory: #'Q2-Serialization-Tests'!
SystemOrganization addCategory: #'Q2-Sessions'!
SystemOrganization addCategory: #'Q2-Settings'!
SystemOrganization addCategory: #'Q2-Soap'!
SystemOrganization addCategory: #'Q2-Stats Mock Utilities'!
SystemOrganization addCategory: #'Q2-Tests'!
SystemOrganization addCategory: #'Q2-Transactions'!
SystemOrganization addCategory: #'Q2-Transactions-Notifications'!
SystemOrganization addCategory: #'Q2-Transactions-Process Editing'!
SystemOrganization addCategory: #'Q2-Transactions-Serialization'!
SystemOrganization addCategory: #'Q2-Transactions-Serialization-Tests'!
SystemOrganization addCategory: #'Q2-Transactions-Tests'!
SystemOrganization addCategory: #'Q2-Translation'!
SystemOrganization addCategory: #'Q2-Utilities'!
SystemOrganization addCategory: #'Q2-Utilities-SwishE'!
SystemOrganization addCategory: #'Q2-Utilities-SwishE-Tests'!
SystemOrganization addCategory: #'Q2-Visualization'!
